### ISSUE TITLE
Source errors

### ISSUE THREAD

**Issue by ghost** [GrapeCity/pagefx#2]
I see a possibility of using this project for developing actual Adobe AIR apps, but when I open the solution in latest Visual Studio it seems something is missing. For example, `PFC.cs` refers to an undefined class `PFCOptions`. Do I need to run some script?

**Comment by ghost** [comment]
According to the blog, it seems latest C# compiler isn't supported, but it's interesting anyway!

**Comment by sergeyt** [comment]
@Klaider this project is dead, but it can be reanimated. And it is not hard 😄
